entorno:
  n_entorno:
    nr: 1.33
    ni: 0.0

fotones:
  lamda: 532
  origen: 0
  dispersion_pos: "uniform"
  dispersion_ang: "uniform"

emision_fuente:
  N_fotones: 1000
  mean_pos_x: 0
  std_pos_x: 0
  mean_pos_y: 0
  std_pos_y: 0
  mean_angle: pi/2
  std_angle: 0
  reset : "True"
  d_ampliacion: 300

estructuras:
  n_estructuras: 1             # Se creará una única esfera
  min_x: -500
  max_x: 500
  min_y: -500
  max_y: 500
  y_fixed: false
  estructuras_aisladas:
    radio: 250
    nr_list: 
      - 1.5
    ni_list:
      - 0.01
    fs_list:
      - 1.0
