entorno:
  n_entorno:
    nr: 1.0
    ni: 0.0

emision_fuente:
  N_fotones: 1000
  mean_pos_x: 0
  std_pos_x: 0
  mean_pos_y: 0
  std_pos_y: 0
  mean_angle: pi/2
  std_angle: 0
  reset : "True"
  d_ampliacion: 300

fotones:
  lamda: 633
  origen: 0
  dispersion_pos: "normal"     # Usa la función GenerateRandomNormalPosition2D
  dispersion_ang: "normal"     # Usa la función GenerateRandomNormalAngle
  
estructuras:
  n_estructuras: 3             # Se crearán 3 esferas aisladas
  min_x: -2000
  max_x: 2000
  min_y: -2000
  max_y: 2000
  y_fixed: false
  estructuras_aisladas:
    radio: 300
    nr_list:
      - 1.5
    ni_list:
      - 0.01
    fs_list:
      - 1.0
